"""empty message

Revision ID: 197a5330d263
Revises: 3eca0e57f30c
Create Date: 2019-11-29 13:39:26.714273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197a5330d263'
down_revision = '3eca0e57f30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('like_num', sa.Integer(), nullable=True))
    op.add_column('note_comment', sa.Column('like_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_comment', 'like_num')
    op.drop_column('note', 'like_num')
    # ### end Alembic commands ###
