"""empty message

Revision ID: 2d30e29d65de
Revises: 197a5330d263
Create Date: 2019-11-29 13:46:20.032638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d30e29d65de'
down_revision = '197a5330d263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_comment', sa.Column('floor', sa.Integer(), nullable=True))
    op.drop_index('floors', table_name='note_comment')
    op.create_unique_constraint(None, 'note_comment', ['floor'])
    op.drop_column('note_comment', 'floors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_comment', sa.Column('floors', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'note_comment', type_='unique')
    op.create_index('floors', 'note_comment', ['floors'], unique=True)
    op.drop_column('note_comment', 'floor')
    # ### end Alembic commands ###
