"""empty message

Revision ID: 3eca0e57f30c
Revises: efd3179f9916
Create Date: 2019-11-29 10:50:30.310833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eca0e57f30c'
down_revision = 'efd3179f9916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(length=50), nullable=True))
    op.drop_column('note', 'sub_title')
    op.drop_column('note', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('note', sa.Column('sub_title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
