"""empty message

Revision ID: 50584c0aea61
Revises: c88aeac7a5e9
Create Date: 2019-11-07 20:54:53.573631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50584c0aea61'
down_revision = 'c88aeac7a5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('lgc_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'lgc_path')
    # ### end Alembic commands ###
