"""empty message

Revision ID: 6c564e7d96d1
Revises: dba580611012
Create Date: 2019-08-27 18:15:00.550029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c564e7d96d1'
down_revision = 'dba580611012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub__comment', sa.Column('to_blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sub__comment', 'blog', ['to_blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub__comment', type_='foreignkey')
    op.drop_column('sub__comment', 'to_blog_id')
    # ### end Alembic commands ###
