"""empty message

Revision ID: 7625fb9de412
Revises: 2bf0b358db32
Create Date: 2019-11-26 22:10:27.047279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7625fb9de412'
down_revision = '2bf0b358db32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_passwd', table_name='user')
    op.drop_column('user', 'passwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwd', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_passwd', 'user', ['passwd'], unique=False)
    # ### end Alembic commands ###
