"""empty message

Revision ID: 97c3f5d6647b
Revises: 50584c0aea61
Create Date: 2019-11-07 20:56:53.228973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97c3f5d6647b'
down_revision = '50584c0aea61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'lgc_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('lgc_path', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
