"""empty message

Revision ID: 99eca89cebc7
Revises: aff5d4b4ab85
Create Date: 2019-10-17 22:38:10.480676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99eca89cebc7'
down_revision = 'aff5d4b4ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
