"""empty message

Revision ID: 9dc238c567bb
Revises: 20b7d2bfd7b9
Create Date: 2019-11-27 22:09:17.312033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc238c567bb'
down_revision = '20b7d2bfd7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note__comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('floors', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('to_note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floors')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note__comment')
    # ### end Alembic commands ###
