"""empty message

Revision ID: aeb8bec79387
Revises: 7e2c5c22f99c
Create Date: 2019-11-01 17:36:55.556362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeb8bec79387'
down_revision = '7e2c5c22f99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('upload_time', sa.DateTime(), nullable=True))
    op.drop_column('note', 'uploud_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('uploud_time', mysql.DATETIME(), nullable=True))
    op.drop_column('note', 'upload_time')
    # ### end Alembic commands ###
