"""empty message

Revision ID: b6b844ad5874
Revises: 688ae74db27d
Create Date: 2019-08-14 12:07:09.603733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b844ad5874'
down_revision = '688ae74db27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('last_cmmt_time', sa.DateTime(), nullable=True),
    sa.Column('like_num', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('like_num', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('to_blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('about_me', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=144), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('passwd', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('tel_num', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_passwd'), 'user', ['passwd'], unique=False)
    op.create_index(op.f('ix_user_tel_num'), 'user', ['tel_num'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tel_num'), table_name='user')
    op.drop_index(op.f('ix_user_passwd'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'tel_num')
    op.drop_column('user', 'passwd')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'email')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'about_me')
    op.drop_table('comment')
    op.drop_table('blog')
    # ### end Alembic commands ###
