"""empty message

Revision ID: ba0e5aa25de3
Revises: b6b844ad5874
Create Date: 2019-08-14 12:14:59.446885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0e5aa25de3'
down_revision = 'b6b844ad5874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('to_cmmt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['to_cmmt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'to_cmmt_id')
    # ### end Alembic commands ###
