"""empty message

Revision ID: bd529fcd5f68
Revises: ba0e5aa25de3
Create Date: 2019-08-23 11:53:19.635275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd529fcd5f68'
down_revision = 'ba0e5aa25de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('cmmt_num', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_3', 'comment', type_='foreignkey')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', mysql.VARCHAR(length=500), nullable=True))
    op.create_foreign_key('comment_ibfk_3', 'comment', 'comment', ['to_cmmt_id'], ['id'])
    op.drop_column('blog', 'cmmt_num')
    # ### end Alembic commands ###
