"""empty message

Revision ID: c1155e57948c
Revises: f054bd4e3392
Create Date: 2019-11-28 21:57:30.629461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1155e57948c'
down_revision = 'f054bd4e3392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_comment', sa.Column('under_cmmt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note_comment', 'note_comment', ['under_cmmt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_comment', type_='foreignkey')
    op.drop_column('note_comment', 'under_cmmt_id')
    # ### end Alembic commands ###
