"""empty message

Revision ID: c88aeac7a5e9
Revises: aeb8bec79387
Create Date: 2019-11-05 12:56:43.001273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c88aeac7a5e9'
down_revision = 'aeb8bec79387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('sub_title', sa.String(length=100), nullable=True))
    op.drop_column('note', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('note', 'sub_title')
    # ### end Alembic commands ###
