"""empty message

Revision ID: d5380f127328
Revises: a401bbf8d04f
Create Date: 2019-12-16 22:15:09.962276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5380f127328'
down_revision = 'a401bbf8d04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'folder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('folder', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
