"""empty message

Revision ID: dd9e6651efa2
Revises: 7625fb9de412
Create Date: 2019-11-26 22:12:24.624156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9e6651efa2'
down_revision = '7625fb9de412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwd', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_passwd'), 'user', ['passwd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_passwd'), table_name='user')
    op.drop_column('user', 'passwd')
    # ### end Alembic commands ###
