"""empty message

Revision ID: ecff309095a1
Revises: 2d30e29d65de
Create Date: 2019-12-16 21:46:24.869053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecff309095a1'
down_revision = '2d30e29d65de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('logic_path', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'logic_path')
    # ### end Alembic commands ###
