"""empty message

Revision ID: efd3179f9916
Revises: c1155e57948c
Create Date: 2019-11-28 22:17:49.977871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd3179f9916'
down_revision = 'c1155e57948c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_comment', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_comment', 'level')
    # ### end Alembic commands ###
