"""empty message

Revision ID: f054bd4e3392
Revises: 9dc238c567bb
Create Date: 2019-11-27 22:23:17.667214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f054bd4e3392'
down_revision = '9dc238c567bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('floors', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('to_note_id', sa.Integer(), nullable=True),
    sa.Column('to_cmmt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_cmmt_id'], ['note_comment.id'], ),
    sa.ForeignKeyConstraint(['to_note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floors')
    )
    op.drop_index('floors', table_name='note__comment')
    op.drop_table('note__comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note__comment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('upload_time', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('floors', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('to_note_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='note__comment_ibfk_1'),
    sa.ForeignKeyConstraint(['to_note_id'], ['note.id'], name='note__comment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('floors', 'note__comment', ['floors'], unique=True)
    op.drop_table('note_comment')
    # ### end Alembic commands ###
